# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: echo.proto for package 'echo'

require 'grpc'
require 'echo_pb'

module Echo
  module Echo
    # The Echo service definition
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'echo.Echo'

      # Simple echo method
      rpc :Echo, ::Echo::EchoRequest, ::Echo::EchoResponse
    end

    Stub = Service.rpc_stub_class
  end
end
